### ISSUE TITLE
Need dark text color.

### ISSUE THREAD

**Issue by utkarsh2102** [vipulgupta2048/Pyladies-delhi-website#33]
Snapshot of present text color is as follows.
![issue2](https://user-images.githubusercontent.com/31288318/40791445-1e61a5ee-6515-11e8-95c3-9d7a1e55335e.png)
The text color in this section (and any other section where this color is used) is light and needs to be darkened in order to increase it's visibility.

**Comment by vipulgupta2048** [comment]
Though corrected.

![screenshot_2018-05-31_21-57-48](https://user-images.githubusercontent.com/22801822/40794745-b655d840-651d-11e8-866f-2133f107bc61.png)

@utkarsh2102 Hi, this has already been fixed. Please do a hard refresh as already mentioned by @thisisayush in #31
Do suggest changes with the updated screenshot that you have in mind.

**Comment by vipulgupta2048** [comment]
@thisisayush Please change the font used in the description, it is too flimsy and light. How about Merriweather or Roboto, as I use in Mixster.

**Comment by utkarsh2102** [comment]
@vipulgupta2048, a darker version of text was required when she reviewed. 
She couldn't read clearly and asked me to make the text (the summary of the activity) more darker to make it's visibility clearer.

**Comment by utkarsh2102** [comment]
Any ETA on this?
@vipulgupta2048 @thisisayush
