### ISSUE TITLE
Only 1 organiser is required.

### ISSUE THREAD

**Issue by utkarsh2102** [vipulgupta2048/Pyladies-delhi-website#34]
The "Organisers" section is presently as follows.
![issue3](https://user-images.githubusercontent.com/31288318/40791670-ad2db542-6515-11e8-99c5-ff744165ebc1.png)
However, there's only 1 organiser, namely Pushplata Ranjan.
Hence the other two, in left and right, should be removed.
If possible, add her name and an appropriate image.

**Comment by thisisayush** [comment]
Can you send me her details ASAP?
