### ISSUE TITLE
Links to be corrected.

### ISSUE THREAD

**Issue by utkarsh2102** [vipulgupta2048/Pyladies-delhi-website#35]
The links for the icon is to be corrected.
Everything has to be linked with PyLadies Delhi.

**Comment by utkarsh2102** [comment]
The links have been corrected in PR#31.
Hence this issue is on hold for sometime.

**Comment by vipulgupta2048** [comment]
@utkarsh2102 Which icons are you referring to specifically.

**Comment by utkarsh2102** [comment]
As peer #31, it seems fixed. 
However, if there's a problem, I'll mention it here or fix it myself.
Hence, kept this issue on hold.
