### ISSUE TITLE
Add a FB icon.

### ISSUE THREAD

**Issue by utkarsh2102** [vipulgupta2048/Pyladies-delhi-website#41]
Amongst the social media icons, there should be another icon for FB added.

**Comment by utkarsh2102** [comment]
CC: @thisisayush

**Comment by vipulgupta2048** [comment]
Why? In a previous review it was removed. Please don't overlap changes. It
was clearly mentioned that the Facebook page doesn't exist. Hence I removed
it. Can you please confirm and send the link here.

**Comment by utkarsh2102** [comment]
Sure.
https://www.facebook.com/PyLadies-Delhi-201302817266313/
Recently made and hence raised an issue :)

**Comment by vipulgupta2048** [comment]
Go ahead
